#include "IgorUnit"
#include "numutils"
#include "stringutils"

Function utest_Num_getUnitMagnitude()
    EXPECT_EQ(3, Num_getUnitMagnitude(1e5))
    EXPECT_EQ(6, Num_getUnitMagnitude(1e6))
End

Static Constant kTOLd = 1e-13          // double precision tolerance
Function utest_Nums_areEqual()
	EXPECT_TRUE(Nums_areEqual(-inf, -inf, tol=kTOLd))
	EXPECT_TRUE(Nums_areEqual(inf, inf, tol=kTOLd))
	EXPECT_TRUE(Nums_areEqual(NaN, NaN, tol=kTOLd))
	EXPECT_TRUE(Nums_areEqual(NaN, -NaN, tol=kTOLd))	// Signed bit of NaN should be ignored
	EXPECT_TRUE(Nums_areEqual(-1, -1, tol=kTOLd))
	EXPECT_TRUE(Nums_areEqual(1, 1, tol=kTOLd))
	EXPECT_TRUE(Nums_areEqual(0, 0, tol=kTOLd))
	EXPECT_TRUE(Nums_areEqual(1, 1, tol=kTOLd))
	EXPECT_TRUE(Nums_areEqual(inf * 0, NaN, tol=kTOLd))
	EXPECT_TRUE(Nums_areEqual(0, 0, tol=kTOLd))
	EXPECT_TRUE(Nums_areEqual(sqrt(-1), NaN, tol=kTOLd))
	EXPECT_TRUE(Nums_areEqual(kTOLd * 0.999, 0, tol=kTOLd))	// due to tolerance
	EXPECT_TRUE(Nums_areEqual(1234567890e256, 1234567890e256, tol=kTOLd))
End

Function utest_Nums_regex()
    EXPECT_STREQ("12", String_getRegexMatch(" 12 ", NUM_REGEX))
    EXPECT_STREQ("1.", String_getRegexMatch(" 1. ", NUM_REGEX))
    EXPECT_STREQ("+1", String_getRegexMatch(" +1 ", NUM_REGEX))
    EXPECT_STREQ("-1", String_getRegexMatch(" -1 ", NUM_REGEX))
    EXPECT_STREQ("+.1", String_getRegexMatch(" +.1 ", NUM_REGEX))
    EXPECT_STREQ("+1.", String_getRegexMatch(" +1. ", NUM_REGEX))
    EXPECT_STREQ(".5", String_getRegexMatch(" ...5", NUM_REGEX))
    EXPECT_STREQ("1.1e+000", String_getRegexMatch(" 1.1e+000", NUM_REGEX))
    EXPECT_STREQ("1.e+2", String_getRegexMatch(" 1.e+2", NUM_REGEX))
    EXPECT_STREQ("1.e-2", String_getRegexMatch(" 1.e-2", NUM_REGEX))
    EXPECT_STREQ("1.2", String_getRegexMatch(" 1.2.3e-2", NUM_REGEX))
    EXPECT_STREQ(".1e-2", String_getRegexMatch(" .1e-2", NUM_REGEX))
    EXPECT_STREQ("-.1e-2", String_getRegexMatch(" -.1e-2", NUM_REGEX))
    EXPECT_STREQ("+.1e-2", String_getRegexMatch(" +.1e-2", NUM_REGEX))
    EXPECT_STREQ("1.e-2", String_getRegexMatch(" 1.e-2", NUM_REGEX))
    EXPECT_STREQ("-1.e-2", String_getRegexMatch(" -1.e-2", NUM_REGEX))
    EXPECT_STREQ("+1.e-2", String_getRegexMatch(" +1.e-2", NUM_REGEX))
    EXPECT_STREQ("-1.234", String_getRegexMatch(" -1.234", NUM_REGEX))
    EXPECT_STREQ("+1.234", String_getRegexMatch(" +1.234", NUM_REGEX))
    EXPECT_STREQ("1.", String_getRegexMatch(" 1..e0", NUM_REGEX))

    EXPECT_STREQ("74.99", String_getRegexMatch("74.99", NUM_REGEX))
    EXPECT_STREQ("7.718", String_getRegexMatch("7.718", NUM_REGEX))
    EXPECT_STREQ("74.99e+000", String_getRegexMatch("74.99e+000", NUM_REGEX))
    EXPECT_STREQ("7.718E+0000", String_getRegexMatch("7.718E+0000e4", NUM_REGEX))
    EXPECT_STREQ("1.", String_getRegexMatch("1...23.4.5", NUM_REGEX))
    EXPECT_STREQ("1.", String_getRegexMatch("1.    ", NUM_REGEX))
    EXPECT_STREQ("", String_getRegexMatch(".    ", NUM_REGEX))
    EXPECT_STREQ(".5", String_getRegexMatch("......5", NUM_REGEX))
    EXPECT_STREQ("-1.234", String_getRegexMatch("-1.234   ", NUM_REGEX))
    EXPECT_STREQ("+1.234", String_getRegexMatch("+1.234", NUM_REGEX))
    EXPECT_STREQ(".1234", String_getRegexMatch(".1234    ", NUM_REGEX))
    EXPECT_STREQ("-.1234e-5", String_getRegexMatch("-.1234e-5", NUM_REGEX))
    EXPECT_STREQ("1.e0", String_getRegexMatch("1.e0  ", NUM_REGEX))
    EXPECT_STREQ("1.e2", String_getRegexMatch(" 1.e2  ", NUM_REGEX))
    EXPECT_STREQ("1.", String_getRegexMatch("1..e0", NUM_REGEX))


    EXPECT_EQ(12, str2num(String_getRegexMatch(" 12 ", NUM_REGEX)))
    EXPECT_EQ(1, str2num(String_getRegexMatch(" 1. ", NUM_REGEX)))
    EXPECT_EQ(1, str2num(String_getRegexMatch(" +1 ", NUM_REGEX)))
    EXPECT_EQ(-1, str2num(String_getRegexMatch(" -1 ", NUM_REGEX)))
    EXPECT_EQ(.1, str2num(String_getRegexMatch(" +.1 ", NUM_REGEX)))
    EXPECT_EQ(1, str2num(String_getRegexMatch(" +1. ", NUM_REGEX)))
    EXPECT_EQ(.5, str2num(String_getRegexMatch(" ...5", NUM_REGEX)))
    EXPECT_EQ(1.1, str2num(String_getRegexMatch(" 1.1e+000", NUM_REGEX)))
    EXPECT_EQ(1e2, str2num(String_getRegexMatch(" 1.e+2", NUM_REGEX)))
    EXPECT_EQ(1e-2, str2num(String_getRegexMatch(" 1.e-2", NUM_REGEX)))
    EXPECT_EQ(1.2, str2num(String_getRegexMatch(" 1.2.3e-2", NUM_REGEX)))
    EXPECT_EQ(.1e-2, str2num(String_getRegexMatch(" .1e-2", NUM_REGEX)))
    EXPECT_EQ(-.1e-2, str2num(String_getRegexMatch(" -.1e-2", NUM_REGEX)))
    EXPECT_EQ(.1e-2, str2num(String_getRegexMatch(" +.1e-2", NUM_REGEX)))
    EXPECT_EQ(1e-2, str2num(String_getRegexMatch(" 1.e-2", NUM_REGEX)))
    EXPECT_EQ(-1e-2, str2num(String_getRegexMatch(" -1.e-2", NUM_REGEX)))
    EXPECT_EQ(+1e-2, str2num(String_getRegexMatch(" +1.e-2", NUM_REGEX)))
    EXPECT_EQ(-1.234, str2num(String_getRegexMatch(" -1.234", NUM_REGEX)))
    EXPECT_EQ(+1.234, str2num(String_getRegexMatch(" +1.234", NUM_REGEX)))
    EXPECT_EQ(1, str2num(String_getRegexMatch(" 1..e0", NUM_REGEX)))

    EXPECT_EQ(74.99, str2num(String_getRegexMatch("74.99", NUM_REGEX)))
    EXPECT_EQ(7.718, str2num(String_getRegexMatch("7.718", NUM_REGEX)))
    EXPECT_EQ(74.99, str2num(String_getRegexMatch("74.99e+000", NUM_REGEX)))
    EXPECT_EQ(7.718, str2num(String_getRegexMatch("7.718E+0000e4", NUM_REGEX)))
    EXPECT_EQ(1, str2num(String_getRegexMatch("1...23.4.5", NUM_REGEX)))
    EXPECT_EQ(1, str2num(String_getRegexMatch("1.    ", NUM_REGEX)))
    EXPECT_EQ(.5, str2num(String_getRegexMatch("......5", NUM_REGEX)))
    EXPECT_EQ(-1.234, str2num(String_getRegexMatch("-1.234   ", NUM_REGEX)))
    EXPECT_EQ(1.234, str2num(String_getRegexMatch("+1.234", NUM_REGEX)))
    EXPECT_EQ(.1234, str2num(String_getRegexMatch(".1234    ", NUM_REGEX)))
    EXPECT_EQ(-.1234e-5, str2num(String_getRegexMatch("-.1234e-5", NUM_REGEX)))
    EXPECT_EQ(1, str2num(String_getRegexMatch("1.e0  ", NUM_REGEX)))
    EXPECT_EQ(100, str2num(String_getRegexMatch("1.e2  ", NUM_REGEX)))
    EXPECT_EQ(1, str2num(String_getRegexMatch("1..e0", NUM_REGEX)))
End
